package com.example.demo.cons

object Cons {
    const val BASE_URL = "http://api.alquran.cloud/v1/"
    var juzzStartingWord = arrayOf("الٓمٓ",
        "سَيَقُول",
        "تِلۡكَ ٱلرُّسُلُ",
        "لَن تَنَالُو",
        "وَٱلۡمُحۡصَنَـٰتُ",
        "لَّا يُحِبُّ ٱللَّهُ",
        "وَإِذَا سَمِعُوا",
        "وَلَوۡ أَنَّنَا",
        "قَالَ ٱلۡمَلَأُ",
        "وَٱعۡلَمُوٓاْ",
        "يَعۡتَذِرُون",
        "وَمَا مِن دَآبَّةٍ",
        "وَمَآ أُبَرِّئُ",
        "رُّبَمَا",
        "سُبۡحَـٰنَ ٱلَّذِىٓ",
        "قَالَ أَلَم",
        "ٱقۡتَرَبَ لِلنَّاسِ",
        "قَدۡ أَفۡلَحَ",
        "وَقَالَ ٱلَّذِينَ",
        "أَمَّنۡ خَلَقَ",
        "ٱتۡلُ مَآ أُوحِىَ",
        "وَمَن يَقۡنُتۡ",
        "وَمَا لِىَ",
        "فَمَنۡ أَظۡلَمُ",
        "إِلَيۡهِ يُرَدُّ",
        "حمٓ",
        "قَالَ فَمَا خَطۡبُكُم",
        "قَدۡ سَمِعَ ٱللَّه",
        "تَبَـٰرَكَ ٱلَّذِى",
        "عَمّ")

    var PARAH_SURAH_AYAH = arrayOf(
        intArrayOf(2, 148),
        intArrayOf(1, 111),
        intArrayOf(2, 126),
        intArrayOf(2, 131),
        intArrayOf(1, 124),
        intArrayOf(2, 110),
        intArrayOf(2, 149),
        intArrayOf(2, 142),
        intArrayOf(2, 159),
        intArrayOf(2, 127),
        intArrayOf(3, 151),
        intArrayOf(2, 170),
        intArrayOf(3, 154),
        intArrayOf(2, 227),
        intArrayOf(2, 185),
        intArrayOf(3, 269),
        intArrayOf(2, 190),
        intArrayOf(3, 202),
        intArrayOf(3, 339),
        intArrayOf(3, 171),
        intArrayOf(5, 178),
        intArrayOf(4, 169),
        intArrayOf(4, 357),
        intArrayOf(3, 175),
        intArrayOf(5, 246),
        intArrayOf(6, 195),
        intArrayOf(7, 399),
        intArrayOf(9, 137),
        intArrayOf(1, 431),
        intArrayOf(37, 564))
}