name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout the code
        run : echo Hello World!
        
        
      - name: Run a multi-line script
        run : echo test and deploy your project!
        
        
        
       
